### PR TITLE
change return type to bool instead of string

### LINKED ISSUE #67: isPayerActive returns a string instead of a boolean.
**Describe the bug**
The function `isPayerActive` in the `src/collections.ts` dir returns a string. 

**Expected behavior**
Should be returning a boolean (I stand to be corrected). 
Let me know so that I can send a PR right away. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by morelmiles**
Fixes #67

### CODE REVIEW

File: src/collections.ts [hunk 1]
```diff
@@ -184,9 +184,10 @@ export default class Collections {
...
     id: string,
     type: PartyIdType = PartyIdType.MSISDN
-  ): Promise<string> {
+  ): Promise<boolean> {
     return this.client
-      .get<string>(`/collection/v1_0/accountholder/${type}/${id}/active`)
-      .then(response => response.data);
+      .get<{result: boolean}>(`/collection/v1_0/accountholder/${type}/${id}/active`)
+      .then(response => response.data)
+      .then(data => data.result ? data.result : false);
```
Comment (ernest-okot) [inline src/collections.ts:191]: The code you have here is a code smell. If `result` was truly a boolean, it should be okay to just return it;

```ts
.then(data => data.result)
```

I'm wondering why you feel the need to add the ternary operator
